---
# General Configuration
title: 22 Digital
timezone: Africa/Johannesburg
description: 22 Digital is a different kind of agency.<br>We don't just work for money,
  nor with simply anyone.<br>Our mission is to change the world. If that's yours;
  let's talk.
logo: "/img/logo/22digital.png"
locale: en_GB
baseurl: ''
url: https://22digital.co.za
permalink: "/:title"
# System
markdown: kramdown
exclude:
- ".github"
- ".sass-cache"
- _site
- ".gitignore"
- ".travis.yml"
- 22digital.sublime-project
- 22digital.code-workspace
- 22digital.sublime-workspace
- CHANGELOG.md
- CNAME
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- _templates
# Collections
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
# Plugins
plugins:
- jemoji
- jekyll-mentions
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-last-modified-at
- jekyll-redirect-from
jekyll-mentions:
  base_url: https://github.com
# Octopress Configuration
post_ext: md # File extension. Can be .html as well.
page_ext: md
## Default templates for posts and pages
post_layout: null
page_layout: null
## Format titles with titlecase?
titlecase: true
## Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
