---
title: 22 Digital
timezone: Africa/Johannesburg
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 22 Digital is a different kind of agency.<br>We don't just work for money,
  nor with simply anyone.<br>Our mission is to change the world. If that's yours;
  let's talk.
logo: "/img/logo/22digital.png"
locale: en_GB
baseurl: ''
url: https://22digital.co.za
permalink: "/:title"
markdown: kramdown
exclude:
- ".github"
- ".sass-cache"
- _site
- ".gitignore"
- ".travis.yml"
- 22digital.sublime-project
- 22digital.code-workspace
- 22digital.sublime-workspace
- CHANGELOG.md
- CNAME
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- _templates
- vendor
plugins:
- jemoji
- jekyll-mentions
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-last-modified-at
- jekyll-redirect-from
jekyll-mentions:
  base_url: https://github.com
post_ext: md
page_ext: md
post_layout:
page_layout:
titlecase: true
post_template: post
page_template: page
draft_template: draft

theme: jekyll-theme-minimal